### ISSUE TITLE
Prediction is not accurate!(Confusion)

### ISSUE THREAD

**Issue by asifehmad** [yasohasakii/unet-segmentation#2]
Hi, sir! Thanks a lot for the code. I am trying to train my own data set using this code for segmentation of skin lesion. It worked. But at the end displaying of prediction results has created confusion. The raw images and the corresponding model results are same. I think the model result should be some black and white image like labels of the raw images, as your training results show. Below are the results of my training:
![github1](https://user-images.githubusercontent.com/54246513/71639866-23c9b580-2ca1-11ea-9ccb-db68b85d0e25.PNG)
![github2](https://user-images.githubusercontent.com/54246513/71639867-23c9b580-2ca1-11ea-833b-829483e9c652.PNG)
![github3](https://user-images.githubusercontent.com/54246513/71639868-24624c00-2ca1-11ea-96c3-36889a43191f.PNG)

I would also like to mention here that most of my images are of 1640x1033 size and I have trained the network for 50 epochs.
Would be very thankful for your response, sir!

**Comment by yasohasakii** [comment]
Sorry for not immidiently reply to you, I tried to download your sample pictures but all failed, if you can not sovle this maybe you can send your pictures to my email: caibojun@myhexin.com.

best wishes!

**Comment by asifehmad** [comment]
Thank you so much for your response. I solved the problem, and all I need was to increase the number of epochs.
